# Checks if the project actually builds
#

name: Build the project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '13'
        check-latest: true
    - name: Install the dependencies
      run: npm install
    - name: Build the project
      run: npm run build

