# Builds the project and copies the contents to root of gh-pages branch
#
name: Publish GHPage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '13'
    - name: Install the dependencies
      run: npm install
    - name: Build the project
      run: npm run build
    - name: Publish to gh-pages branch
      run: |
        git checkout gh-pages
        cp -a build/. $(pwd)
        git config --global user.email actions@github.com
        git config --global user.name Github Actions
        git commit -m "$GITHUB_SHA"
        git push origin gh-pages

